name: CI/CD - Angular + Express

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   backend:
      runs-on: ubuntu-latest
      defaults:
         run:
            working-directory: ExpressECommmerce
      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: Install backend dependencies
           run: npm ci

         - name: Run backend tests
           run: npm test

   frontend:
      runs-on: ubuntu-latest
      needs: backend
      defaults:
         run:
            working-directory: eCommerce_Front
      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: Install frontend dependencies
           run: npm ci

         - name: Lint frontend
           run: npm run lint

         - name: Run frontend tests
           run: npm run test -- --watch=false --browsers=ChromeHeadless

         - name: Build Angular app
           run: npm run build -- --configuration production
